name: Trigger auto deployment for container-app-7dr6gabeyuh5k

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/container-app-7dr6gabeyuh5k-AutoDeployTrigger-6d63c388-eaaf-4fe2-b114-fd0dfb2e7fda.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPP7DR6GABEYUH5K_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPP7DR6GABEYUH5K_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPP7DR6GABEYUH5K_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: containerregistry7dr6gabeyuh5k.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPP7DR6GABEYUH5K_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPP7DR6GABEYUH5K_REGISTRY_PASSWORD }}
          containerAppName: container-app-7dr6gabeyuh5k
          resourceGroup: expresssamplea2b48e3d
          imageToBuild: containerregistry7dr6gabeyuh5k.azurecr.io/container-app-7dr6gabeyuh5k:${{ github.sha }}
          


